### ISSUE TITLE
Cannot find /usr/local/otb/bin/otbcli_BandMath

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE-flavors#28]
This cannot be found by the Cimpal cell. In original docker file, we have the following:

```Dockerfile
WORKDIR /usr/local/otb

RUN wget https://www.orfeo-toolbox.org/packages/archives/OTB/OTB-7.3.0-Linux64.run &&  \
    chmod +x OTB-7.3.0-Linux64.run && \
    ./OTB-7.3.0-Linux64.run --target $PWD
```

Which is also included in the flavor: https://github.com/QCDIS/NaaVRE-flavors/blob/main/flavors/biotope/naavre-cell-runtime.Dockerfile

Need to figure out why /usr/local/otb/bin/otbcli_BandMath is not found.

**Comment by gpelouze** [comment]
The cell was containerized with the python base image: https://github.com/QCDIS/NaaVRE-cells-test-2/blob/a52f9bb2b611e1cf8ddc5cd1d40854cb11437680/cimpal2-chenkaiwei0527-gmail-com/Dockerfile#L11

```Dockerfile
FROM ghcr.io/qcdis/naavre/naavre-cell-runtime-python:v0.5-alpha.4 AS runtime
```

@Ckkk112138, can you try rebuilding with the biotope base image?

**Comment by Ckkk112138** [comment]
@gpelouze I checked the Base Image area but no biotope was found. Only can see 5 base images.

**Comment by gpelouze** [comment]
@Ckkk112138 I just deployed the new release. Can you restart your Jupyter Lab (menu File > Logout, then login again) and try again? I can see all base images now. 

![image](https://github.com/QCDIS/NaaVRE-flavors/assets/9514702/e18fac12-accc-4a9b-aa36-e80e0c221fa6)

**Comment by Ckkk112138** [comment]
@gpelouze Yes, I can see all the images now. The Cimpal workflow is now running successfully to completion.
