### ISSUE TITLE
rs-insitu-comp-zhanqing2016 keeps pending because the containerization failed

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE-flavors#38]
The problem for that seems to be that we haven't set the correct mapping for the dt tools:

#12 34.69 The following packages are incompatible
#12 34.69 ├─ r-dtlife does not exist (perhaps a typo or a missing channel);
#12 34.69 ├─ r-dtpp does not exist (perhaps a typo or a missing channel);
#12 34.69 └─ r-dtwad does not exist (perhaps a typo or a missing channel).

**Comment by skoulouzis** [comment]
We need to install:

devtools::install_github("LTER-LIFE/dtR/dtLife", depend=TRUE)

after which you can install the dtWad package:

devtools::install_github("LTER-LIFE/dtR/dtWad", depend=TRUE)

and the dtPP package:

devtools::install_github("LTER-LIFE/dtR/dtPP", depend=TRUE)

**Comment by gpelouze** [comment]
Users should keep installing dtR on runtime for now. It doesn’t make sense to include it in the base image because it is under active development.
